name: flutter_ledger_lib
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  convert: ^3.0.2
  ffi: ^1.2.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  synchronized: ^3.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^6.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: FlutterLedgerLibPlugin
      windows:
        pluginClass: FlutterLedgerLibPluginCApi

ffigen:
  name: "Bindings"
  description: "Generated bindings"
  output: "lib/src/bindings.g.dart"
  llvm-path:
    - "/opt/homebrew/opt/llvm@11"
  headers:
    entry-points:
      - "rust/target/bindings.h"